version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=contact_dev
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - 5050:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: project@project.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data:
  pgadmin_data:

